### ISSUE TITLE
When use import in main.js, It has errors.

### ISSUE THREAD

**Issue by Andyliwr** [InCuca/vue-loopback#7]
When use import in main.js, It has errors.
![2018-04-26 10 04 26](https://user-images.githubusercontent.com/12456160/39310759-d2631480-499d-11e8-8e2d-23eac3914984.png)

**Comment by Andyliwr** [comment]
I just import as this.
![2018-04-26 10 05 55](https://user-images.githubusercontent.com/12456160/39310839-0cdfdae4-499e-11e8-8384-9c6a56159ad4.png)

**Comment by klarkc** [comment]
the build failed at demooo package, can you list it using `npm ls demooo`? I think probably this package is not compiled to ES5

**Comment by klarkc** [comment]
Update: I've added a new feature, with this feature you can compile ES6 modules, just insert the module that you want to import in bModules variable of `gulp-tasks/build.js` file
