### ISSUE TITLE
SASS: Problem with relative path in Windows

### ISSUE THREAD

**Issue by ruriba** [InCuca/vue-loopback#8]
There is a problem compiling the client from Windows, causing problems with the relative SASS paths. I've replaced the backslashes on the routes and apparently that solves the problem.

> /gulp-task/compiler.js

~line 17
```
const relativePath = path.relative(
    path.dirname(filePath),
    path.resolve(dirs.srcClient, 'style/global.scss')
).replace(/\\/g,'/'); // Replace backslashes with forward slashes
```

**Comment by klarkc** [comment]
Thanks for contribution, please report more windows bugs if you find something else. :+1:
